# @name REQUEST_ONE
POST https://httpbin.org/post HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer Foo:bar

{
  "deep": {
    "nested": [
      {
        "key": "foo"
      },
    ]
  }
}
